version: "3.8"
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
  order-service:
    build: ./order-service
    ports:
      - "8082:8080"
  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
