server:
  port: 8080

spring:
  graphql:
    schema:
      locations: classpath:/nowhere/ # disable local schema loading

dgs:
  graphql:
    schema-locations: []
    federation:
      enabled: true
      services:
        - name: user-service
          url: http://localhost:8081/graphql
        - name: order-service
          url: http://localhost:8082/graphql

logging:
  level:
    com.netflix.graphql.dgs.federation: DEBUG
    com.netflix.graphql.dgs.webmvc: DEBUG
