server:
  port: 8082

spring:
  graphql:
    schema:
      locations: classpath:/schema/

dgs:
  graphql:
    federation:
      enabled: true

logging:
  level:
    com.netflix.graphql.dgs.federation: DEBUG
    com.netflix.graphql.dgs.webmvc: DEBUG 